apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: db:5432
    database: timeseries
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
      timescaledb: true
    isDefault: true
    editable: true
